// svelte/src/lib/searchbar.svelte
<div class="join">
    <input bind:value={search_query} type="text" placeholder="Search..." class=" join-item input input-bordered max-w-xs" />
    <a class="btn btn-outline btn-secondary join-item" href="/search-result?search={search_query}">
        <LupaIcon />
    </a>
</div>

<script>
    import LupaIcon from '$lib/img/icon/common/lupa.svg?component'
    let search_query = ''
</script>

// nuxt/components/searchbar.vue
<template>
    <div class="join">
        <input v-model="searchQuery" type="text" placeholder="Search..." class=" join-item input input-bordered max-w-xs" />
        <NuxtLink class="btn btn-outline btn-secondary join-item" :to="`/search-result?search=${searchQuery}`">
            <icon-common-lupa />
        </NuxtLink>
    </div>
</template>

<script>

// import { useRouter } from 'vue-router';
import { useNuxtApp } from 'nuxt/app';

export default {
  name: 'searchbar',
  setup() {

    // const router = useRouter()
    const searchQuery = ref('')

    const router = useNuxtApp().router

    return {
      router, searchQuery
    }
  }
}
</script>
