// svelte/src/lib/searchbar.svelte
<div class="join">
    <input bind:value={search_query} type="text" placeholder="Search..." class=" join-item input input-bordered max-w-xs" />
    <a class="btn btn-outline btn-secondary join-item" href="/search-result?search={search_query}">
        <LupaIcon />
    </a>
</div>

<script>
    import LupaIcon from '$lib/img/icon/common/lupa.svg?component'
    let search_query = ''
</script>

// vue/src/components/searchbar.vue
<template>
    <div class="join">
        <input type="text" placeholder="Search..." class=" join-item input input-bordered max-w-xs" />
        <button class="btn btn-outline btn-secondary join-item">
        <svg 
            xmlns="http://www.w3.org/2000/svg" 
            width="24" 
            height="24" 
            viewBox="0 0 24 24" 
            fill="none" 
            stroke="currentColor" 
            stroke-width="2" 
            stroke-linecap="round" 
            stroke-linejoin="round"
        >
            <circle cx="11" cy="11" r="8"></circle>
            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
        </svg>
        </button>
    </div>
</template>

<script>
export default {
  name: 'searchbar',
  setup() {
    return {
    }
  }
}
</script>

<style>
</style>
