// svelte/src/routes/this-project/+page.svelte
<div class=" flex flex-wrap min-h-full">
    <h1 class=" text-3xl w-full text-primary text-center m-auto">this.project</h1>
    <p class=" text-center m-auto">
        This project is a showcase of my skills and knowledge. It is also a
        playground for me to try out new technologies and ideas.
    </p>
</div>

// nuxt/pages/this-project.vue
<template>
  <div class=" flex flex-wrap min-h-full">
    <h1 class=" text-3xl w-full text-primary text-center m-auto">this.project</h1>
    <p class=" text-center m-auto">
      This project is a showcase of my skills and knowledge. It is also a
      playground for me to try out new technologies and ideas.
    </p>
  </div>
</template>
