// nuxt/components/layout/footer.vue
<template>
    <footer class="footer items-center p-4 bg-base-200 text-neutral-content">
        <aside class="flex items-center grid-flow-col gap-4">
            <icon-blog />
            <p class="">© 2023 Daniel Sykora. Všechna práva vyhrazena.</p>
        </aside> 
        <nav class=" flex gap-4 justify-between w-full md:w-min md:justify-self-end">
            <a><icon-twitter/>  </a>
            <a><icon-youtube/>  </a>
            <a><icon-facebook/> </a>
            <a><icon-github/>   </a>
        </nav>
    </footer>
</template>

// svelte/src/lib/footer.svelte
<footer class="footer items-center p-4 bg-base-200 text-neutral-content">
    <aside class="flex items-center grid-flow-col gap-4">
        <icon-blog />
        <p class="">© 2023 Daniel Sykora. Všechna práva vyhrazena.</p>
    </aside> 
    <nav class=" flex gap-4 justify-between w-full md:w-min md:justify-self-end">
        <a href=" "><TwitterIcon class="fill-current"/> </a>
        <a href=" "><YoutubeIcon class="fill-current"/> </a>
        <a href=" "><FacebookIcon class="fill-current"/> </a>
        <a href=" "><GithubIcon class="fill-current"/> </a>
    </nav>
</footer>

<script>
    import TwitterIcon from "$lib/img/icon/social/twitter.svg?component";
    import YoutubeIcon from "$lib/img/icon/social/youtube.svg?component";
    import FacebookIcon from "$lib/img/icon/social/facebook.svg?component";
    import GithubIcon from "$lib/img/icon/social/github.svg?component";
</script>
